try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

setup(
    name='nate-blackbox-natrix',
    version='1.0.0',
    url='https://github.com/NateAI/nate.blackbox.natrix',
    author='nate',
    author_email='ds@nate.tech',
    license='MIT',
    description='A machine learning model for web automation',
    packages=['tv_net'],
    install_requires=['numpy>=1.16.4',
                      'scipy>=1.3.0',
                      'tensorflow-gpu>=1.14.0',
                      'beautifulsoup4>=4.7.1',
                      'flask>==1.1.1',
                      'graphviz>=0.11',
                      'ipython>=7.6.0',
                      'keras>=2.2.4',
                      'lxml>=4.1.1',
                      'matplotlib>=3.0.3',
                      'opencv-python>=4.1.0.25',
                      'Pillow>=6.0.0',
                      'pandas>=0.24.2',
                      'psycopg2-binary>==2.7.7',
                      'pydot>=1.4.1',
                      'pymongo>=3.8.0',
                      'requests>==2.22.0',
                      'scikit-image>=0.15.0',
                      'scikit-learn>=0.21.2',
                      'tabulate>=0.8.3',
                      'xlrd>=1.2.0',
                      'XlsxWriter>=1.0.2']
    , dependency_links=['git+git@github.com:NateAI/nate.blackbox.common.git#egg=nate-blackbox-common',
                        'git+git@github.com:NateAI/nate.blackbox.mrcnn.git@urgent_mrcnn_changes#egg=mrcnn',
                        'git+https://github.com/IDSIA/sacred.git@3a7419621caf473c195697506726a9fe2c21cae0#egg=sacred',
                        ],
    include_package_data=True,
    python_requires='>=3.4',
    long_description='''Natrix model.''',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Scientific/Engineering :: Visualization',
        'Programming Language :: Python :: 3'
    ],
    keywords='weakly-supervised learning label noise',
)
